spring:
  config:
    import: optional:file:internal.env[.properties]
  datasource:
    url: jdbc:${DB_JDBC_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB_NAME:SocialSonic}
    username: ${DB_USER:Sonic}
    password: ${DB_PASSWORD:ChangeMe}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: SocialSonic
  main:
    banner-mode: off
server:
  tomcat:
    threads:
      max: ${SCS_TOMCAT_THREADS:75}
