spring.application.name=SocialSonic
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/SocialSonic
spring.datasource.password=${SPRING_PASS}
spring.datasource.username=Sonic
spring.jpa.hibernate.ddl-auto=update
