spring:
  config:
    import: optional:file:internal.env[.properties]
  datasource:
    url: jdbc:${DB_JDBC_TYPE}://${DB_HOST}:${DB_PORT}/${DB_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: SocialSonic